## 어텐션(Attention)

### 맥락 벡터 : 단어 벡터에 가중치를 를 곱하여 합한 가중합을 구한 벡터
단어를 선택하는 작업은 미분 불가하므로 모든 것을 선택하고 단어의 중요도를 가중치로 계산

In [13]:
import numpy as np
np.random.seed(100)

T,H = 5,4       # T : 시계열의 길이, H : Hidden size
hs = np.random.randn(T,H)  # (5,4)
print('hs:\n',hs)
print('hs0:', hs[0])

a  = np.array([0.8, 0.1, 0.03, 0.05, 0.02]) # 가중치, (5,)
print('a:',a, np.sum(a))

# (1) repeat() 함수
ar = a.reshape(T,1).repeat(4,axis=1) # (5,1)로 2차원으로 shape을 바꾸고 수평 방향으로 4번 반복 복사
print('ar:\n',ar)
print(ar.shape)   # (5, 4)

t = hs * ar       # (5,4) * (5,4) : 요소간의 곱셈, 단어벡터에 가중치를 곱함
print('t:\n',t)

# (2) Numpy 브로드캐스팅 사용, 1번과 결과 동일 
ar = a.reshape(T,1) # (5,1)로 2차원으로 shape을 바꿈
print('ar:\n',ar)
print(ar.shape)   # (5, 1)

t = hs * ar       # (5,4) * (5,1) : 브로드캐스팅 적용, 요소간의 곱셈, 단어벡터에 가중치를 곱함
print('t:\n',t)
print(t.shape)    # (5, 4)

#  가중합을 계산하여 맥락 벡터를 구한다
c = np.sum(t,axis=0)  # 수직 방햡으로 합 , 가중합, 맥락 벡터
print('c  :',c)       # [-1.34717053  0.39465326  0.95567913 -0.32348518], hs0와 거의 비슷한 값들로 hs0을 선택한 효과
print('hs0:',hs[0])   # [-1.74976547  0.3426804   1.1530358  -0.25243604]
print(c.shape)        # (4,)

hs:
 [[-1.74976547  0.3426804   1.1530358  -0.25243604]
 [ 0.98132079  0.51421884  0.22117967 -1.07004333]
 [-0.18949583  0.25500144 -0.45802699  0.43516349]
 [-0.58359505  0.81684707  0.67272081 -0.10441114]
 [-0.53128038  1.02973269 -0.43813562 -1.11831825]]
hs0: [-1.74976547  0.3426804   1.1530358  -0.25243604]
a: [0.8  0.1  0.03 0.05 0.02] 1.0
ar:
 [[0.8  0.8  0.8  0.8 ]
 [0.1  0.1  0.1  0.1 ]
 [0.03 0.03 0.03 0.03]
 [0.05 0.05 0.05 0.05]
 [0.02 0.02 0.02 0.02]]
(5, 4)
t:
 [[-1.39981238  0.27414432  0.92242864 -0.20194883]
 [ 0.09813208  0.05142188  0.02211797 -0.10700433]
 [-0.00568487  0.00765004 -0.01374081  0.0130549 ]
 [-0.02917975  0.04084235  0.03363604 -0.00522056]
 [-0.01062561  0.02059465 -0.00876271 -0.02236636]]
ar:
 [[0.8 ]
 [0.1 ]
 [0.03]
 [0.05]
 [0.02]]
(5, 1)
t:
 [[-1.39981238  0.27414432  0.92242864 -0.20194883]
 [ 0.09813208  0.05142188  0.02211797 -0.10700433]
 [-0.00568487  0.00765004 -0.01374081  0.0130549 ]
 [-0.02917975  0.04084235  0.03363604 -0.00522056]
 