## Repeat 노드

In [6]:
import numpy as np

# 순전파

D = 8
N = 7
x = np.random.rand(1,D)  # (1,8)
print(x,x.shape)
print('-'*70)
y = np.repeat(x,N,axis=0) # 수직(행) 방향, axis=0
print(y,y.shape)  # (7, 8)

[[0.27109315 0.49767331 0.56927947 0.42296008 0.31214592 0.97042406
  0.1148904  0.57108899]] (1, 8)
----------------------------------------------------------------------
[[0.27109315 0.49767331 0.56927947 0.42296008 0.31214592 0.97042406
  0.1148904  0.57108899]
 [0.27109315 0.49767331 0.56927947 0.42296008 0.31214592 0.97042406
  0.1148904  0.57108899]
 [0.27109315 0.49767331 0.56927947 0.42296008 0.31214592 0.97042406
  0.1148904  0.57108899]
 [0.27109315 0.49767331 0.56927947 0.42296008 0.31214592 0.97042406
  0.1148904  0.57108899]
 [0.27109315 0.49767331 0.56927947 0.42296008 0.31214592 0.97042406
  0.1148904  0.57108899]
 [0.27109315 0.49767331 0.56927947 0.42296008 0.31214592 0.97042406
  0.1148904  0.57108899]
 [0.27109315 0.49767331 0.56927947 0.42296008 0.31214592 0.97042406
  0.1148904  0.57108899]] (7, 8)


In [9]:
# 역전파
dy = np.random.rand(N,D)
print(dy,dy.shape) # (7,8)
print('-'*70)
dx = np.sum(dy,axis=0,keepdims=True) # 수직방향 합, keepdims=True이면 2차원, False면 1차원
print(dx,dx.shape)  # (1, 8)

[[0.74496688 0.36126302 0.82668043 0.78312498 0.88463831 0.5573557
  0.39782022 0.36979402]
 [0.37585922 0.97853225 0.05766467 0.94680112 0.52509762 0.26122901
  0.66129044 0.28651123]
 [0.58052625 0.05209089 0.70347782 0.01395558 0.89732362 0.69030329
  0.75305341 0.4024679 ]
 [0.6904399  0.91843254 0.18853904 0.98264296 0.97471993 0.94760274
  0.39053649 0.04603387]
 [0.0987068  0.25890584 0.34184181 0.90291012 0.36294027 0.43182508
  0.28957317 0.24073662]
 [0.56596023 0.82031256 0.28717695 0.40460966 0.73949866 0.22061768
  0.91967058 0.68696397]
 [0.20279732 0.49862034 0.4285634  0.39698631 0.1799669  0.77089222
  0.20664471 0.50825278]] (7, 8)
----------------------------------------------------------------------
[[3.25925659 3.88815743 2.83394412 4.43103072 4.56418531 3.87982572
  3.61858902 2.5407604 ]] (1, 8)


## Sum 노드

In [12]:
# 순전파

D,N = 8,7
x = np.random.rand(N,D)  # (7,8)
print(x,x.shape)
print('-'*70)
y = np.sum(x,axis=0,keepdims=True) # 수직방향 합, keepdims=True이면 2차원, False면 1차원
print(y,y.shape)  # (1, 8)

[[0.94230331 0.56879603 0.65019912 0.80259791 0.82977032 0.40919536
  0.40223097 0.49958372]
 [0.94069933 0.76630945 0.69838869 0.51756749 0.75185235 0.71360236
  0.6128462  0.06977631]
 [0.74779111 0.61935969 0.12040902 0.9091499  0.63145503 0.2045993
  0.8471794  0.28351313]
 [0.92317901 0.22622485 0.90339955 0.85054769 0.47360163 0.56006906
  0.60257561 0.22436932]
 [0.64664273 0.38748978 0.82311867 0.80091692 0.02631415 0.9381065
  0.2019493  0.07259553]
 [0.08977557 0.10005677 0.37370554 0.29864666 0.88788716 0.90186169
  0.04179442 0.70721164]
 [0.88909779 0.47866752 0.08385894 0.85078855 0.94836581 0.93143564
  0.14568606 0.48034667]] (7, 8)
----------------------------------------------------------------------
[[5.17948885 3.14690409 3.65307953 5.03021511 4.54924646 4.6588699
  2.85426195 2.33739633]] (1, 8)


In [13]:
#역전파

D = 8
N = 7
x = np.random.rand(1,D)  # (1,8)
print(x,x.shape)
print('-'*70)
y = np.repeat(x,N,axis=0) # 수직(행) 방향, axis=0
print(y,y.shape)  # (7, 8)

[[0.72075423 0.75751497 0.48963828 0.77795596 0.38884289 0.84143849
  0.6986215  0.75796798]] (1, 8)
----------------------------------------------------------------------
[[0.72075423 0.75751497 0.48963828 0.77795596 0.38884289 0.84143849
  0.6986215  0.75796798]
 [0.72075423 0.75751497 0.48963828 0.77795596 0.38884289 0.84143849
  0.6986215  0.75796798]
 [0.72075423 0.75751497 0.48963828 0.77795596 0.38884289 0.84143849
  0.6986215  0.75796798]
 [0.72075423 0.75751497 0.48963828 0.77795596 0.38884289 0.84143849
  0.6986215  0.75796798]
 [0.72075423 0.75751497 0.48963828 0.77795596 0.38884289 0.84143849
  0.6986215  0.75796798]
 [0.72075423 0.75751497 0.48963828 0.77795596 0.38884289 0.84143849
  0.6986215  0.75796798]
 [0.72075423 0.75751497 0.48963828 0.77795596 0.38884289 0.84143849
  0.6986215  0.75796798]] (7, 8)


## MatMul 노드

In [18]:
class MatMul:
    def __init__(self,W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None
        
    def forward(self,x):
        W = self.params
        out = np.dot(x,W)
        self.x
        return out
    
    def backward(self,dout):
        W = self.params
        dx = np.dot(dout,W.T)
        dW = np.dot(selg.x.T,dout)
        self.grads[0][...] = dw  # 깊은 복사
        return dx        

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a = b
print(a)
id(a) == id(b)

[4 5 6]


True

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a[...] = b
print(a)
id(a) == id(b)

[4 5 6]


False

In [17]:
# np.zeros_like
a = np.arange(12).reshape(3,4)
b = np.zeros_like(a)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])