## Repeat 노드

In [1]:
import numpy as np

# 순전파

D = 8
N = 7
x = np.random.rand(1,D)  # (1,8)
print(x,x.shape)
print('-'*70)
y = np.repeat(x,N,axis=0) # 수직(행) 방향, axis=0
print(y,y.shape)  # (7, 8)

[[0.52781263 0.97286701 0.38888237 0.53222858 0.2224099  0.38495747
  0.12059257 0.76510621]] (1, 8)
----------------------------------------------------------------------
[[0.52781263 0.97286701 0.38888237 0.53222858 0.2224099  0.38495747
  0.12059257 0.76510621]
 [0.52781263 0.97286701 0.38888237 0.53222858 0.2224099  0.38495747
  0.12059257 0.76510621]
 [0.52781263 0.97286701 0.38888237 0.53222858 0.2224099  0.38495747
  0.12059257 0.76510621]
 [0.52781263 0.97286701 0.38888237 0.53222858 0.2224099  0.38495747
  0.12059257 0.76510621]
 [0.52781263 0.97286701 0.38888237 0.53222858 0.2224099  0.38495747
  0.12059257 0.76510621]
 [0.52781263 0.97286701 0.38888237 0.53222858 0.2224099  0.38495747
  0.12059257 0.76510621]
 [0.52781263 0.97286701 0.38888237 0.53222858 0.2224099  0.38495747
  0.12059257 0.76510621]] (7, 8)


In [2]:
# 역전파
dy = np.random.rand(N,D)
print(dy,dy.shape) # (7,8)
print('-'*70)
dx = np.sum(dy,axis=0,keepdims=True) # 수직방향 합, keepdims=True이면 2차원, False면 1차원
print(dx,dx.shape)  # (1, 8)

[[0.05051161 0.92046602 0.74464169 0.11493337 0.31160336 0.11636491
  0.86639924 0.24619157]
 [0.31855904 0.00735901 0.92810823 0.94930472 0.08278947 0.87219092
  0.7095227  0.06142227]
 [0.15357785 0.32640322 0.82331333 0.9836446  0.58166202 0.0111699
  0.01353731 0.86140361]
 [0.40436167 0.62460307 0.41230121 0.65390828 0.21233881 0.27445325
  0.48096127 0.41496532]
 [0.02149247 0.86799273 0.0014539  0.8337664  0.77688202 0.38300503
  0.04646075 0.52660719]
 [0.512755   0.45123398 0.1870406  0.33081956 0.36481371 0.68229871
  0.63401982 0.94995147]
 [0.26522045 0.16140957 0.95686626 0.78619958 0.85361849 0.07642411
  0.74091676 0.9360373 ]] (7, 8)
----------------------------------------------------------------------
[[1.7264781  3.35946762 4.05372521 4.65257652 3.18370788 2.41590682
  3.49181786 3.99657872]] (1, 8)


## Sum 노드

In [3]:
# 순전파

D,N = 8,7
x = np.random.rand(N,D)  # (7,8)
print(x,x.shape)
print('-'*70)
y = np.sum(x,axis=0,keepdims=True) # 수직방향 합, keepdims=True이면 2차원, False면 1차원
print(y,y.shape)  # (1, 8)

[[0.50363913 0.42285661 0.50033386 0.15786793 0.41346745 0.82639798
  0.52089699 0.65303515]
 [0.9520493  0.02816572 0.15816886 0.47118711 0.61270055 0.34575245
  0.19411853 0.31812849]
 [0.62114003 0.47145639 0.85532117 0.24643182 0.53705214 0.34009574
  0.24686807 0.37382494]
 [0.14363399 0.30855732 0.20444118 0.13451595 0.4236308  0.53324504
  0.16026627 0.57449044]
 [0.19068842 0.40921259 0.35856784 0.97704517 0.75484719 0.3954346
  0.78287182 0.19587096]
 [0.53672052 0.82493644 0.97268654 0.06290922 0.87102271 0.24115837
  0.26034133 0.63262435]
 [0.92428693 0.1889949  0.36977863 0.43300551 0.12818967 0.96454601
  0.31569538 0.10105209]] (7, 8)
----------------------------------------------------------------------
[[3.87215832 2.65417997 3.41929808 2.48296271 3.74091052 3.64663018
  2.48105839 2.84902642]] (1, 8)


In [4]:
#역전파

D = 8
N = 7
x = np.random.rand(1,D)  # (1,8)
print(x,x.shape)
print('-'*70)
y = np.repeat(x,N,axis=0) # 수직(행) 방향, axis=0
print(y,y.shape)  # (7, 8)

[[0.06190169 0.21432366 0.41796928 0.48630209 0.6765318  0.40324439
  0.99919614 0.94452115]] (1, 8)
----------------------------------------------------------------------
[[0.06190169 0.21432366 0.41796928 0.48630209 0.6765318  0.40324439
  0.99919614 0.94452115]
 [0.06190169 0.21432366 0.41796928 0.48630209 0.6765318  0.40324439
  0.99919614 0.94452115]
 [0.06190169 0.21432366 0.41796928 0.48630209 0.6765318  0.40324439
  0.99919614 0.94452115]
 [0.06190169 0.21432366 0.41796928 0.48630209 0.6765318  0.40324439
  0.99919614 0.94452115]
 [0.06190169 0.21432366 0.41796928 0.48630209 0.6765318  0.40324439
  0.99919614 0.94452115]
 [0.06190169 0.21432366 0.41796928 0.48630209 0.6765318  0.40324439
  0.99919614 0.94452115]
 [0.06190169 0.21432366 0.41796928 0.48630209 0.6765318  0.40324439
  0.99919614 0.94452115]] (7, 8)


## MatMul 노드

In [5]:
class MatMul:
    def __init__(self,W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None
        
    def forward(self,x):
        W = self.params
        out = np.dot(x,W)
        self.x = x
        return out
    
    def backward(self,dout):
        W = self.params
        dx = np.dot(dout,W.T)
        dW = np.dot(self.x.T,dout)
        self.grads[0][...] = dw  # 깊은 복사
        return dx        

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a = b
print(a)
id(a) == id(b)

[4 5 6]


True

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a[...] = b
print(a)
id(a) == id(b)

[4 5 6]


False

In [8]:
# np.zeros_like
a = np.arange(12).reshape(3,4)
b = np.zeros_like(a)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 시그모이드 계층

In [9]:
class Sigmoid:
    def __init__(self):
        self.params,self.grads = [],[]
        self.out = None
        
    def forward(self,x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out
    
    def backward(self,dout):
        dx = dout * self.out * (1 - self.out)  # 공식 도출은 참고서적 참조
        return dx

## Affine 계층 : MatMul 노드 에 bias를  더한 계층 

In [11]:
class Affine:
    def __init__(self,W,b):
        self.params = [W,b]
        self.grads = [np.zeros_like(W),np.zeros_like(b)]
        self.x = None
        
    def forward(self,x):
        W, b = self.params
        out = np.dot(x,W) + b
        self.x = x
        return out 
    
    def backward(self,dout):
        W, = self.params
        dx = np.dot(dout,W.T)
        dW = np.dot(self.x.T,dout)
        db = np.sum(dout,axis=0)
        
        self.grads[0][...] = dW
        self.grads[1][...] = db
        return dx

In [12]:
a = np.zeros_like([[1,2,3]]) # 인자와 shape이 같은 배열을 모든 요소를 0으로 생성
print(a,type(a))

[[0 0 0]] <class 'numpy.ndarray'>


## Softmax with Loss 계층

In [13]:
class SoftmaxWithLoss:
    def __init__(self):
        self.params,self.grads = [], []
        self.y = None    # softmax의 출력 값
        self.t = None    # 정답 레이블
        
    def softmax(self,x):
        if x.ndim == 2:
            x = x - x.max(axis=1, keepdims=True)
            x = np.exp(x)
            x /= x.sum(axis=1, keepdims=True)
        elif x.ndim == 1:
            x = x - np.max(x)
            x = np.exp(x) / np.sum(np.exp(x))
        return x 
    
    def cross_entropy_error(self,y, t):
        if y.ndim == 1:
            t = t.reshape(1, t.size)
            y = y.reshape(1, y.size)

        # 정답 데이터가 원핫 벡터일 경우 정답 레이블 인덱스로 변환
        if t.size == y.size:
            t = t.argmax(axis=1)

        batch_size = y.shape[0]

        return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size
          
    
    def forward(self, x, t):
        self.t = t
        self.y = self.softmax(x)

        # 정답 레이블이 원핫 벡터일 경우 정답의 인덱스로 변환
        if self.t.size == self.y.size:
            self.t = self.t.argmax(axis=1)

        loss = self.cross_entropy_error(self.y, self.t)
        return loss
     